IF OBJECT_ID('Sph.SearchDefinition', 'U') IS NOT NULL
  DROP TABLE Sph.SearchDefinition
GO

CREATE TABLE Sph.SearchDefinition
(
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL
	,[Entity] VARCHAR(255) NOT NULL
	,[Json] VARCHAR(MAX) NOT NULL
	,[Name] VARCHAR(255) NOT NULL
	,[OwnerType] VARCHAR(255) NOT NULL
	,[Owner] VARCHAR(255) NOT NULL
	,[IsPublished] BIT NOT NULL
	,[Route] VARCHAR(255) NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 