 IF OBJECT_ID('Sph.Designation', 'U') IS NOT NULL
  DROP TABLE Sph.Designation
GO

CREATE TABLE [Sph].[Designation](
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL,
	[Name] VARCHAR(255) NOT NULL,
	[Json] VARCHAR(MAX) NOT NULL	,
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] VARCHAR(255) NULL,
	[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ChangedBy] VARCHAR(255) NULL
	)
GO


