 IF OBJECT_ID('Sph.ReportDefinition', 'U') IS NOT NULL
  DROP TABLE Sph.ReportDefinition
GO

CREATE TABLE [Sph].[ReportDefinition](
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL,
	[Title] VARCHAR(255) NOT NULL	,
	[Description] VARCHAR(2000) NULL,
	[IsActive] BIT NOT NULL	,
	[IsPrivate] BIT NOT NULL,
	[Json] VARCHAR(MAX) NOT NULL, 
	[DataSource.EntityName] VARCHAR(255) NOT NULL DEFAULT '',
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] VARCHAR(255) NULL,
	[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ChangedBy] VARCHAR(255) NULL
	)
GO



