
IF OBJECT_ID('Sph.Adapter', 'U') IS NOT NULL
  DROP TABLE Sph.Adapter
GO

CREATE TABLE Sph.Adapter
(
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL
	,[Json] NVARCHAR(MAX) NOT NULL
	,[Name] VARCHAR(255) NULL
	,[Description] VARCHAR(255) NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 
