IF OBJECT_ID('Sph.EmailTemplate', 'U') IS NOT NULL
  DROP TABLE Sph.EmailTemplate
GO

CREATE TABLE Sph.EmailTemplate
(
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL
	,[Entity] VARCHAR(255) NOT NULL
	,[Json] VARCHAR(MAX) NOT NULL
	,[Name] VARCHAR(255) NOT NULL
	,[IsPublished] BIT NOT NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL
)
GO 