IF OBJECT_ID('Sph.SpatialStore', 'U') IS NOT NULL
  DROP TABLE Sph.SpatialStore
GO

CREATE TABLE Sph.SpatialStore
(
	[Id] VARCHAR(255) PRIMARY KEY NOT NULL
	,[Json] VARCHAR(MAX) NOT NULL
	,[Type] VARCHAR(255) NULL
	,[StoreId] VARCHAR(255) NULL
	,[Tag] VARCHAR(255) NULL
	,[Path] GEOGRAPHY NULL
	,[Wkt] VARCHAR(MAX) NULL 
	,[EncodedWkt] VARCHAR(MAX) NULL
	,[SearchText] VARCHAR(255) NULL
	,[CreatedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[CreatedBy] VARCHAR(255) NULL
	,[ChangedDate] SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,[ChangedBy] VARCHAR(255) NULL

)
GO 
