//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class intakeEntities : DbContext
    {
        public intakeEntities()
            : base("name=intakeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcqCriteria> tblAcqCriterias { get; set; }
        public virtual DbSet<tblAcqEducationCriteria> tblAcqEducationCriterias { get; set; }
        public virtual DbSet<tblAcqEducationCriteriaSubject> tblAcqEducationCriteriaSubjects { get; set; }
        public virtual DbSet<tblAcqEduCriteriaFieldOfStudy> tblAcqEduCriteriaFieldOfStudies { get; set; }
        public virtual DbSet<tblAcqQuestion> tblAcqQuestions { get; set; }
        public virtual DbSet<tblAcqQuestionnaire> tblAcqQuestionnaires { get; set; }
        public virtual DbSet<tblAcqQuestionnaireScale> tblAcqQuestionnaireScales { get; set; }
        public virtual DbSet<tblAcquisition> tblAcquisitions { get; set; }
        public virtual DbSet<tblApplicant> tblApplicants { get; set; }
        public virtual DbSet<tblApplicantDispStatu> tblApplicantDispStatus { get; set; }
        public virtual DbSet<tblApplicantEdu> tblApplicantEdus { get; set; }
        public virtual DbSet<tblApplicantEduSubject> tblApplicantEduSubjects { get; set; }
        public virtual DbSet<tblApplicantSkill> tblApplicantSkills { get; set; }
        public virtual DbSet<tblApplicantSportAssoc> tblApplicantSportAssocs { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblREFAchievement> tblREFAchievements { get; set; }
        public virtual DbSet<tblREFAcqType> tblREFAcqTypes { get; set; }
        public virtual DbSet<tblRefBloodType> tblRefBloodTypes { get; set; }
        public virtual DbSet<tblREFCity> tblREFCities { get; set; }
        public virtual DbSet<tblREFCountry> tblREFCountries { get; set; }
        public virtual DbSet<tblREFEthnic> tblREFEthnics { get; set; }
        public virtual DbSet<tblREFGender> tblREFGenders { get; set; }
        public virtual DbSet<tblREFHighEduLevel> tblREFHighEduLevels { get; set; }
        public virtual DbSet<tblREFInstitution> tblREFInstitutions { get; set; }
        public virtual DbSet<tblREFInstitutionCat> tblREFInstitutionCats { get; set; }
        public virtual DbSet<tblREFLoginStatu> tblREFLoginStatus { get; set; }
        public virtual DbSet<tblREFMajorMinor> tblREFMajorMinors { get; set; }
        public virtual DbSet<tblREFMaritalStatu> tblREFMaritalStatus { get; set; }
        public virtual DbSet<tblREFPersonalityType> tblREFPersonalityTypes { get; set; }
        public virtual DbSet<tblREFQuestionnareType> tblREFQuestionnareTypes { get; set; }
        public virtual DbSet<tblREFRace> tblREFRaces { get; set; }
        public virtual DbSet<tblREFReligion> tblREFReligions { get; set; }
        public virtual DbSet<tblREFService> tblREFServices { get; set; }
        public virtual DbSet<tblREFSkill> tblREFSkills { get; set; }
        public virtual DbSet<tblREFSkillCat> tblREFSkillCats { get; set; }
        public virtual DbSet<tblREFSportAndAssociation> tblREFSportAndAssociations { get; set; }
        public virtual DbSet<tblREFState> tblREFStates { get; set; }
        public virtual DbSet<tblREFSubject> tblREFSubjects { get; set; }
        public virtual DbSet<tblREFSubjectGrade> tblREFSubjectGrades { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserLog> tblUserLogs { get; set; }
    }
}
