//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcqMerit
    {
        public tblAcqMerit()
        {
            this.tblAcqMeritScores = new HashSet<tblAcqMeritScore>();
        }
    
        public int AcqMeritId { get; set; }
        public int AcquisitionId { get; set; }
        public string MeritTypeCd { get; set; }
        public Nullable<bool> MeritInd { get; set; }
    
        public virtual tblREFMeritType tblREFMeritType { get; set; }
        public virtual ICollection<tblAcqMeritScore> tblAcqMeritScores { get; set; }
        public virtual tblAcquisition tblAcquisition { get; set; }
    }
}
