//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppApplicantMeritScore
    {
        public int AppApplicantMeritScore { get; set; }
        public int AcquisitionId { get; set; }
        public int AppId { get; set; }
        public Nullable<decimal> OverallAcademicScore { get; set; }
        public Nullable<decimal> AcademicScore { get; set; }
        public string AcademicHighEduLevelCd { get; set; }
        public Nullable<decimal> BMScore { get; set; }
        public Nullable<decimal> MathScore { get; set; }
        public Nullable<decimal> SCScore { get; set; }
        public Nullable<decimal> BIScore { get; set; }
        public Nullable<decimal> OverallWrittenTestScore { get; set; }
        public Nullable<decimal> WrittenIQTestScore { get; set; }
        public Nullable<decimal> WrittenPsychologyTestScore { get; set; }
        public Nullable<decimal> OverallPhysicalScore { get; set; }
        public Nullable<decimal> PhysicalHeightScore { get; set; }
        public Nullable<decimal> PhysicalWeightScore { get; set; }
        public Nullable<decimal> PhysicalBMIScore { get; set; }
        public Nullable<decimal> OverallPhysicalTestScore { get; set; }
        public Nullable<decimal> PhysicalTestRunningScore { get; set; }
        public Nullable<decimal> PhysicalTestMendaguScore { get; set; }
        public Nullable<decimal> PhysicalTestSitUpScore { get; set; }
        public Nullable<decimal> PhysicalTestBroadJumpScore { get; set; }
        public Nullable<decimal> OverallSportInvolvementScore { get; set; }
        public string AchievementCd { get; set; }
        public Nullable<int> SportAssocId { get; set; }
        public Nullable<decimal> OverallMeritScore { get; set; }
    
        public virtual tblApplication tblApplication { get; set; }
        public virtual tblREFHighEduLevel tblREFHighEduLevel { get; set; }
        public virtual tblAcquisition tblAcquisition { get; set; }
    }
}
