//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblAcqEduCriteriaFieldOfStudy
    {
        public int AcqEduCriFOS { get; set; }
        public Nullable<int> AcqEduCriteriaId { get; set; }
        public string MajorMinorCd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual tblAcqEducationCriteria tblAcqEducationCriteria { get; set; }
        public virtual tblREFMajorMinor tblREFMajorMinor { get; set; }
    }
}
