//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcquisition
    {
        public tblAcquisition()
        {
            this.tblAcqCriterias = new HashSet<tblAcqCriteria>();
            this.tblAcqEducationCriterias = new HashSet<tblAcqEducationCriteria>();
            this.tblAcqQuestionnaires = new HashSet<tblAcqQuestionnaire>();
            this.tblApplications = new HashSet<tblApplication>();
        }
    
        public int AcquisitionId { get; set; }
        public string AcquisitionTypeCd { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Siri { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> Target { get; set; }
        public Nullable<bool> NewStatus { get; set; }
        public string NewStatusBy { get; set; }
        public Nullable<bool> OpenStatus { get; set; }
        public string OpenStatusBy { get; set; }
        public Nullable<bool> CloseStatus { get; set; }
        public string CloseStatusBy { get; set; }
        public Nullable<bool> InviteFirstSelStatus { get; set; }
        public string InviteFirstSelStatusBy { get; set; }
        public Nullable<bool> SecurityCheckStatus { get; set; }
        public string SecurityCheckStatusBy { get; set; }
        public Nullable<bool> FirstSelectionStatus { get; set; }
        public string FirstSelectionStatusBy { get; set; }
        public Nullable<bool> InviteFinalSelStatus { get; set; }
        public string InviteFinalSelStatusBy { get; set; }
        public Nullable<bool> WrittenTestStatus { get; set; }
        public string WrittenTestStatusBy { get; set; }
        public Nullable<bool> FinalSelStatus { get; set; }
        public string FinalSelStatusBy { get; set; }
        public Nullable<bool> AssignNoTenteraStatus { get; set; }
        public string AssignNoTenteraStatusBy { get; set; }
        public Nullable<bool> CompleteStatus { get; set; }
        public string CompleteStatusBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblAcqCriteria> tblAcqCriterias { get; set; }
        public virtual ICollection<tblAcqEducationCriteria> tblAcqEducationCriterias { get; set; }
        public virtual ICollection<tblAcqQuestionnaire> tblAcqQuestionnaires { get; set; }
        public virtual tblREFAcqType tblREFAcqType { get; set; }
        public virtual ICollection<tblApplication> tblApplications { get; set; }
    }
}
