//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantSkillSubmitted
    {
        public int ApplicantSkillId { get; set; }
        public int ApplicantId { get; set; }
        public string SkillCd { get; set; }
        public string SkillCatCd { get; set; }
        public Nullable<bool> LanguageSkillSpeak { get; set; }
        public Nullable<bool> LanguageSkillWrite { get; set; }
        public string AchievementCd { get; set; }
        public string Others { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplicantSubmited tblApplicantSubmited { get; set; }
        public virtual tblREFAchievement tblREFAchievement { get; set; }
        public virtual tblREFSkill tblREFSkill { get; set; }
        public virtual tblREFSkillCat tblREFSkillCat { get; set; }
    }
}
