//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppApplicantPhysicalExamination
    {
        public tblAppApplicantPhysicalExamination()
        {
            this.tblAppApplicantPhysicalExamIllnesses = new HashSet<tblAppApplicantPhysicalExamIllness>();
        }
    
        public int AppApplicantPhysicalId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> SelectionInd { get; set; }
        public string PhysicalExamineVenue { get; set; }
        public Nullable<System.DateTime> PhysicalExamineDate { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ChestRegular { get; set; }
        public Nullable<decimal> ChestExpended { get; set; }
        public string ChestLeft { get; set; }
        public string ChestRight { get; set; }
        public string EyeLeft { get; set; }
        public string EyeRight { get; set; }
        public Nullable<bool> ColorBlind { get; set; }
        public string EyeStatusCd { get; set; }
        public Nullable<bool> FlatFoot { get; set; }
        public Nullable<bool> BendHand { get; set; }
        public string MedicalExamineCenter { get; set; }
        public Nullable<System.DateTime> MedicalExamineDate { get; set; }
        public string BloodTypeCd { get; set; }
        public Nullable<bool> DrugSensitive { get; set; }
        public string UrineTest { get; set; }
        public Nullable<bool> UrineTestResult { get; set; }
        public string BloodPreasure { get; set; }
        public string XRayExamineCenter { get; set; }
        public Nullable<System.DateTime> XRayExamineDate { get; set; }
        public string XRayReferrence { get; set; }
        public string DeseaseRemark { get; set; }
        public string MedDiseaseCd { get; set; }
        public Nullable<bool> PhysicalExaminationStatus { get; set; }
        public Nullable<bool> MedicalExamineStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblAppApplicantPhysicalExamIllness> tblAppApplicantPhysicalExamIllnesses { get; set; }
        public virtual tblApplication tblApplication { get; set; }
        public virtual tblRefBloodType tblRefBloodType { get; set; }
        public virtual tblREFEyeStatu tblREFEyeStatu { get; set; }
    }
}
