//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblApplicantSkill
    {
        public int ApplicantSkillId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string SkillCd { get; set; }
        public string SkillCatCd { get; set; }
        public Nullable<bool> LanguageSkillSpeak { get; set; }
        public Nullable<bool> LanguageSkillWrite { get; set; }
        public string AchievementCd { get; set; }
        public string Others { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplicant tblApplicant { get; set; }
        public virtual tblREFAchievement tblREFAchievement { get; set; }
        public virtual tblREFSkill tblREFSkill { get; set; }
        public virtual tblREFSkillCat tblREFSkillCat { get; set; }
    }
}
