//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblApplicantEdu
    {
        public tblApplicantEdu()
        {
            this.tblApplicantEduSubjects = new HashSet<tblApplicantEduSubject>();
        }
    
        public int ApplicantEduId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string HighEduLevelCd { get; set; }
        public string EduCertTitle { get; set; }
        public string OverallGrade { get; set; }
        public Nullable<int> SKMLevel { get; set; }
        public Nullable<int> ConfermentYr { get; set; }
        public string InstCd { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<bool> OverSeaInd { get; set; }
        public string MajorMinorCd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplicant tblApplicant { get; set; }
        public virtual tblREFHighEduLevel tblREFHighEduLevel { get; set; }
        public virtual tblREFInstitution tblREFInstitution { get; set; }
        public virtual tblREFMajorMinor tblREFMajorMinor { get; set; }
        public virtual ICollection<tblApplicantEduSubject> tblApplicantEduSubjects { get; set; }
    }
}
