//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFMajorMinor
    {
        public tblREFMajorMinor()
        {
            this.tblAcqEduCriteriaFieldOfStudies = new HashSet<tblAcqEduCriteriaFieldOfStudy>();
            this.tblApplicantEdus = new HashSet<tblApplicantEdu>();
        }
    
        public string MajorMinorCd { get; set; }
        public string MajorMinor { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblAcqEduCriteriaFieldOfStudy> tblAcqEduCriteriaFieldOfStudies { get; set; }
        public virtual ICollection<tblApplicantEdu> tblApplicantEdus { get; set; }
    }
}
