//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFApplicationStatu
    {
        public tblREFApplicationStatu()
        {
            this.tblApplicationStatus = new HashSet<tblApplicationStatu>();
        }
    
        public string ApplicationStatusCd { get; set; }
        public string ApplicationStatus { get; set; }
    
        public virtual ICollection<tblApplicationStatu> tblApplicationStatus { get; set; }
    }
}
