//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFAchievement
    {
        public tblREFAchievement()
        {
            this.tblApplicantSkills = new HashSet<tblApplicantSkill>();
            this.tblApplicantSportAssocs = new HashSet<tblApplicantSportAssoc>();
        }
    
        public string AchievementCd { get; set; }
        public string Achievement { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblApplicantSkill> tblApplicantSkills { get; set; }
        public virtual ICollection<tblApplicantSportAssoc> tblApplicantSportAssocs { get; set; }
    }
}
