//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFCity
    {
        public tblREFCity()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
        }
    
        public string CityCd { get; set; }
        public string City { get; set; }
        public string StateCd { get; set; }
        public Nullable<bool> StateCapitalInd { get; set; }
        public Nullable<bool> MainCityInd { get; set; }
    
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
        public virtual tblREFState tblREFState { get; set; }
    }
}
