//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFSubjectGrade
    {
        public tblREFSubjectGrade()
        {
            this.tblAcqEducationCriteriaSubjects = new HashSet<tblAcqEducationCriteriaSubject>();
            this.tblApplicantEduSubjects = new HashSet<tblApplicantEduSubject>();
        }
    
        public string GradeCd { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblAcqEducationCriteriaSubject> tblAcqEducationCriteriaSubjects { get; set; }
        public virtual ICollection<tblApplicantEduSubject> tblApplicantEduSubjects { get; set; }
    }
}
