//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFService
    {
        public tblREFService()
        {
            this.tblREFAcqTypes = new HashSet<tblREFAcqType>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public string ServiceCd { get; set; }
        public string Service { get; set; }
    
        public virtual ICollection<tblREFAcqType> tblREFAcqTypes { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
