//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFSportAndAssociation
    {
        public tblREFSportAndAssociation()
        {
            this.tblApplicantSportAssocs = new HashSet<tblApplicantSportAssoc>();
        }
    
        public int SportAssocId { get; set; }
        public string SportAssociatType { get; set; }
        public string SportAssociatName { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblApplicantSportAssoc> tblApplicantSportAssocs { get; set; }
    }
}
