//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFAcqType
    {
        public tblREFAcqType()
        {
            this.tblAcquisitions = new HashSet<tblAcquisition>();
        }
    
        public string AcquisitionTypeCd { get; set; }
        public string AcquisitionTypeNm { get; set; }
        public string ServiceCd { get; set; }
    
        public virtual ICollection<tblAcquisition> tblAcquisitions { get; set; }
        public virtual tblREFService tblREFService { get; set; }
    }
}
