//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFCity
    {
        public tblREFCity()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
            this.tblApplicantSubmiteds = new HashSet<tblApplicantSubmited>();
            this.tblApplicantSubmiteds1 = new HashSet<tblApplicantSubmited>();
            this.tblRefLocations = new HashSet<tblRefLocation>();
        }
    
        public string CityCd { get; set; }
        public string City { get; set; }
        public string StateCd { get; set; }
        public Nullable<bool> StateCapitalInd { get; set; }
        public Nullable<bool> MainCityInd { get; set; }
    
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
        public virtual ICollection<tblApplicantSubmited> tblApplicantSubmiteds { get; set; }
        public virtual ICollection<tblApplicantSubmited> tblApplicantSubmiteds1 { get; set; }
        public virtual tblREFState tblREFState { get; set; }
        public virtual ICollection<tblRefLocation> tblRefLocations { get; set; }
    }
}
