//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblRefBloodType
    {
        public tblRefBloodType()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
        }
    
        public string BloodTypeCd { get; set; }
        public string BloodType { get; set; }
    
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
    }
}
