//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string LoginId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string AlternativeEmail { get; set; }
        public string ServiceCd { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> FirstTime { get; set; }
        public Nullable<System.DateTime> LastLoginDt { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string ModifiedBy { get; set; }
    }
}
