//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class atmEntities : DbContext
    {
        public atmEntities()
            : base("name=atmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcqAnnouncement> tblAcqAnnouncements { get; set; }
        public virtual DbSet<tblAcqCriteria> tblAcqCriterias { get; set; }
        public virtual DbSet<tblAcqEducationCriteria> tblAcqEducationCriterias { get; set; }
        public virtual DbSet<tblAcqEducationCriteriaSubject> tblAcqEducationCriteriaSubjects { get; set; }
        public virtual DbSet<tblAcqEduCriteriaFieldOfStudy> tblAcqEduCriteriaFieldOfStudies { get; set; }
        public virtual DbSet<tblAcqLocation> tblAcqLocations { get; set; }
        public virtual DbSet<tblAcqMerit> tblAcqMerits { get; set; }
        public virtual DbSet<tblAcqMeritScore> tblAcqMeritScores { get; set; }
        public virtual DbSet<tblAcqQuestion> tblAcqQuestions { get; set; }
        public virtual DbSet<tblAcqQuestionnaire> tblAcqQuestionnaires { get; set; }
        public virtual DbSet<tblAcqQuestionnaireScale> tblAcqQuestionnaireScales { get; set; }
        public virtual DbSet<tblAdvertisement_Xpakai> tblAdvertisement_Xpakai { get; set; }
        public virtual DbSet<tblAdvertisment> tblAdvertisments { get; set; }
        public virtual DbSet<tblAppApplicantDentalExamination> tblAppApplicantDentalExaminations { get; set; }
        public virtual DbSet<tblAppApplicantMeritScore> tblAppApplicantMeritScores { get; set; }
        public virtual DbSet<tblAppApplicantPhysicalExamIllness> tblAppApplicantPhysicalExamIllnesses { get; set; }
        public virtual DbSet<tblAppApplicantPhysicalExamination> tblAppApplicantPhysicalExaminations { get; set; }
        public virtual DbSet<tblAppApplicantPhysicalTest> tblAppApplicantPhysicalTests { get; set; }
        public virtual DbSet<tblAppDocumentStatu> tblAppDocumentStatus { get; set; }
        public virtual DbSet<tblApplicant> tblApplicants { get; set; }
        public virtual DbSet<tblApplicantDispStatu> tblApplicantDispStatus { get; set; }
        public virtual DbSet<tblApplicantDispStatusSubmitted> tblApplicantDispStatusSubmitteds { get; set; }
        public virtual DbSet<tblApplicantEdu> tblApplicantEdus { get; set; }
        public virtual DbSet<tblApplicantEduSubject> tblApplicantEduSubjects { get; set; }
        public virtual DbSet<tblApplicantEduSubjectSubmitted> tblApplicantEduSubjectSubmitteds { get; set; }
        public virtual DbSet<tblApplicantEduSubmitted> tblApplicantEduSubmitteds { get; set; }
        public virtual DbSet<tblApplicantPhoto> tblApplicantPhotoes { get; set; }
        public virtual DbSet<tblApplicantSkill> tblApplicantSkills { get; set; }
        public virtual DbSet<tblApplicantSkillSubmitted> tblApplicantSkillSubmitteds { get; set; }
        public virtual DbSet<tblApplicantSportAssoc> tblApplicantSportAssocs { get; set; }
        public virtual DbSet<tblApplicantSportAssocSubmitted> tblApplicantSportAssocSubmitteds { get; set; }
        public virtual DbSet<tblApplicantSubmited> tblApplicantSubmiteds { get; set; }
        public virtual DbSet<tblApplicantSubmittedPhoto> tblApplicantSubmittedPhotoes { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblAppQuestionFeedback> tblAppQuestionFeedbacks { get; set; }
        public virtual DbSet<tblAppQuestionnaireScore> tblAppQuestionnaireScores { get; set; }
        public virtual DbSet<tblExistingAtmMember> tblExistingAtmMembers { get; set; }
        public virtual DbSet<tblREFAchievement> tblREFAchievements { get; set; }
        public virtual DbSet<tblREFApplicationStatu> tblREFApplicationStatus { get; set; }
        public virtual DbSet<tblRefBloodType> tblRefBloodTypes { get; set; }
        public virtual DbSet<tblREFCity> tblREFCities { get; set; }
        public virtual DbSet<tblREFCountry> tblREFCountries { get; set; }
        public virtual DbSet<tblREFDocument> tblREFDocuments { get; set; }
        public virtual DbSet<tblREFEthnic> tblREFEthnics { get; set; }
        public virtual DbSet<tblREFExistingMemberStatu> tblREFExistingMemberStatus { get; set; }
        public virtual DbSet<tblREFEyeStatu> tblREFEyeStatus { get; set; }
        public virtual DbSet<tblREFGender> tblREFGenders { get; set; }
        public virtual DbSet<tblREFHighEduLevel> tblREFHighEduLevels { get; set; }
        public virtual DbSet<tblREFInstitution> tblREFInstitutions { get; set; }
        public virtual DbSet<tblREFInstitutionCat> tblREFInstitutionCats { get; set; }
        public virtual DbSet<tblRefLocation> tblRefLocations { get; set; }
        public virtual DbSet<tblREFLocationZone> tblREFLocationZones { get; set; }
        public virtual DbSet<tblREFLoginStatu> tblREFLoginStatus { get; set; }
        public virtual DbSet<tblREFMajorMinor> tblREFMajorMinors { get; set; }
        public virtual DbSet<tblREFMaritalStatu> tblREFMaritalStatus { get; set; }
        public virtual DbSet<tblREFMedDisease> tblREFMedDiseases { get; set; }
        public virtual DbSet<tblREFMeritType> tblREFMeritTypes { get; set; }
        public virtual DbSet<tblREFOccupation> tblREFOccupations { get; set; }
        public virtual DbSet<tblREFPersonalityType> tblREFPersonalityTypes { get; set; }
        public virtual DbSet<tblREFQuestionnaireSubType> tblREFQuestionnaireSubTypes { get; set; }
        public virtual DbSet<tblREFQuestionnaireType> tblREFQuestionnaireTypes { get; set; }
        public virtual DbSet<tblREFRace> tblREFRaces { get; set; }
        public virtual DbSet<tblREFReligion> tblREFReligions { get; set; }
        public virtual DbSet<tblREFService> tblREFServices { get; set; }
        public virtual DbSet<tblREFSkill> tblREFSkills { get; set; }
        public virtual DbSet<tblREFSkillCat> tblREFSkillCats { get; set; }
        public virtual DbSet<tblREFSportAndAssociation> tblREFSportAndAssociations { get; set; }
        public virtual DbSet<tblREFState> tblREFStates { get; set; }
        public virtual DbSet<tblREFSubject> tblREFSubjects { get; set; }
        public virtual DbSet<tblREFSubjectGrade> tblREFSubjectGrades { get; set; }
        public virtual DbSet<tblREFTalentCat> tblREFTalentCats { get; set; }
        public virtual DbSet<tblREFUserCat> tblREFUserCats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAcqFinalShorlistCriteria> tblAcqFinalShorlistCriterias { get; set; }
        public virtual DbSet<tblApplicationStatu> tblApplicationStatus { get; set; }
        public virtual DbSet<tblREFQuestionnareType> tblREFQuestionnareTypes { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblAcquisition> tblAcquisitions { get; set; }
        public virtual DbSet<tblREFAcqType> tblREFAcqTypes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserLog> tblUserLogs { get; set; }
        public virtual DbSet<tblREFReportDutyLoc> tblREFReportDutyLocs { get; set; }
    }
}
