//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcqMeritScore
    {
        public int AcqMeritScoreId { get; set; }
        public int AcqMeritId { get; set; }
        public string GradeCd { get; set; }
        public Nullable<decimal> CGPAFrom { get; set; }
        public Nullable<decimal> CGPATo { get; set; }
        public string GenderCd { get; set; }
        public string AchievementCd { get; set; }
        public string ValueFrom { get; set; }
        public string ValueTo { get; set; }
        public Nullable<bool> MeritInd { get; set; }
        public Nullable<int> MeritScore { get; set; }
    
        public virtual tblAcqMerit tblAcqMerit { get; set; }
        public virtual tblREFAchievement tblREFAchievement { get; set; }
        public virtual tblREFGender tblREFGender { get; set; }
        public virtual tblREFSubjectGrade tblREFSubjectGrade { get; set; }
    }
}
