//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppApplicantPhysicalTest
    {
        public int AppApplicantPhysicalTestId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> SelectionInd { get; set; }
        public string PhysicalTestVenue { get; set; }
        public Nullable<decimal> Running { get; set; }
        public string RunningRemark { get; set; }
        public Nullable<int> Mendagu { get; set; }
        public string MendaguRemark { get; set; }
        public Nullable<int> SitUp { get; set; }
        public string SitUpRemark { get; set; }
        public Nullable<decimal> BroadJump { get; set; }
        public string BroadJumpRemark { get; set; }
        public Nullable<int> Jump { get; set; }
        public string JumpRemark { get; set; }
        public Nullable<int> PushUp { get; set; }
        public string PushUpRemark { get; set; }
        public string OverallRemark { get; set; }
        public Nullable<bool> PhysicalTestStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplication tblApplication { get; set; }
    }
}
