//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcqAnnouncement
    {
        public int AcqAnnouncementId { get; set; }
        public int AcquisitionId { get; set; }
        public Nullable<int> AnnouncementSelectionInd { get; set; }
        public string AnnouncementTypeInd { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public string AttachmentFileName { get; set; }
        public string AttachmentOriginalFileName { get; set; }
        public Nullable<bool> AnnouncementStatusInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblAcquisition tblAcquisition { get; set; }
    }
}
