//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppQuestionFeedback
    {
        public int AppQstnFeedback { get; set; }
        public Nullable<int> AppId { get; set; }
        public Nullable<int> AcqQuestionId { get; set; }
        public Nullable<int> QuestionnaireScaleId { get; set; }
        public Nullable<bool> SubmitStatus { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblAcqQuestion tblAcqQuestion { get; set; }
        public virtual tblAcqQuestionnaireScale tblAcqQuestionnaireScale { get; set; }
        public virtual tblApplication tblApplication { get; set; }
    }
}
