//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblAcqQuestion
    {
        public int AcqQuestionId { get; set; }
        public Nullable<int> QuestionnaireId { get; set; }
        public string Statement { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> PersonalityYesMark { get; set; }
        public Nullable<int> PersonalityNoMark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual tblAcqQuestionnaire tblAcqQuestionnaire { get; set; }
    }
}
