//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppApplicantDentalExamination
    {
        public int AppApplicantDentalExamineId { get; set; }
        public Nullable<int> AppId { get; set; }
        public string DentallExamineVenue { get; set; }
        public Nullable<System.DateTime> DentalExamineDate { get; set; }
        public string Dval { get; set; }
        public string Eval { get; set; }
        public string Nval { get; set; }
        public string Tval { get; set; }
        public string Aval { get; set; }
        public string Pval { get; set; }
        public Nullable<bool> DentalStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplication tblApplication { get; set; }
    }
}
