//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcqQuestion
    {
        public tblAcqQuestion()
        {
            this.tblAppQuestionFeedbacks = new HashSet<tblAppQuestionFeedback>();
        }
    
        public int AcqQuestionId { get; set; }
        public Nullable<int> QuestionnaireId { get; set; }
        public string Statement { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> PersonalityYesMark { get; set; }
        public Nullable<int> PersonalityNoMark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual tblAcqQuestionnaire tblAcqQuestionnaire { get; set; }
        public virtual ICollection<tblAppQuestionFeedback> tblAppQuestionFeedbacks { get; set; }
    }
}
