//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblAcqQuestionnaireScale
    {
        public int QuestionnaireScaleId { get; set; }
        public Nullable<int> QuestionnaireId { get; set; }
        public Nullable<int> Scale { get; set; }
        public string ScaleRemark { get; set; }
        public Nullable<int> MeritMark { get; set; }
    
        public virtual tblAcqQuestionnaire tblAcqQuestionnaire { get; set; }
    }
}
