//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblApplicantEduSubject
    {
        public int EduSubjectId { get; set; }
        public Nullable<int> ApplicantEduId { get; set; }
        public string SubjectCd { get; set; }
        public string GradeCd { get; set; }
        public string Grade { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<DateTime> LastModifiedDt { get; set; }
    
        public virtual tblApplicantEdu tblApplicantEdu { get; set; }
        public virtual tblREFSubject tblREFSubject { get; set; }
        public virtual tblREFSubjectGrade tblREFSubjectGrade { get; set; }
    }
}
