//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExistingAtmMember
    {
        public int COID { get; set; }
        public string ICNOBaru { get; set; }
        public string NoTentera { get; set; }
        public string CONm { get; set; }
        public string ExistingMemberStatusCd { get; set; }
    
        public virtual tblREFExistingMemberStatu tblREFExistingMemberStatu { get; set; }
    }
}
