//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFMeritType
    {
        public tblREFMeritType()
        {
            this.tblAcqMerits = new HashSet<tblAcqMerit>();
        }
    
        public string MeritTypeCd { get; set; }
        public string MeritType { get; set; }
    
        public virtual ICollection<tblAcqMerit> tblAcqMerits { get; set; }
    }
}
