//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFLoginStatu
    {
        public tblREFLoginStatu()
        {
            this.tblUserLogs = new HashSet<tblUserLog>();
        }
    
        public string LoginStatusCd { get; set; }
        public string LoginStatusNm { get; set; }
    
        public virtual ICollection<tblUserLog> tblUserLogs { get; set; }
    }
}
