//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFSkillCat
    {
        public tblREFSkillCat()
        {
            this.tblApplicantSkills = new HashSet<tblApplicantSkill>();
            this.tblApplicantSkillSubmitteds = new HashSet<tblApplicantSkillSubmitted>();
            this.tblREFSkills = new HashSet<tblREFSkill>();
        }
    
        public string SkillCatCd { get; set; }
        public string SkillCat { get; set; }
    
        public virtual ICollection<tblApplicantSkill> tblApplicantSkills { get; set; }
        public virtual ICollection<tblApplicantSkillSubmitted> tblApplicantSkillSubmitteds { get; set; }
        public virtual ICollection<tblREFSkill> tblREFSkills { get; set; }
    }
}
