//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFAcqType
    {
        public tblREFAcqType()
        {
            this.tblAcquisitions = new HashSet<tblAcquisition>();
        }
    
        public int AcquisitionTypeCd { get; set; }
        public string AcquisitionTypeNm { get; set; }
        public string ServiceCd { get; set; }
    
        public virtual ICollection<tblAcquisition> tblAcquisitions { get; set; }
    }
}
