//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFLocationZone
    {
        public tblREFLocationZone()
        {
            this.tblAcqLocations = new HashSet<tblAcqLocation>();
        }
    
        public string ZoneCd { get; set; }
        public string ZoneNm { get; set; }
    
        public virtual ICollection<tblAcqLocation> tblAcqLocations { get; set; }
    }
}
