//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Entity.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFRace
    {
        public tblREFRace()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
            this.tblApplicantSubmiteds = new HashSet<tblApplicantSubmited>();
            this.tblREFEthnics = new HashSet<tblREFEthnic>();
        }
    
        public string RaceCd { get; set; }
        public string Race { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
        public Nullable<int> SequenceNo { get; set; }
    
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
        public virtual ICollection<tblApplicantSubmited> tblApplicantSubmiteds { get; set; }
        public virtual ICollection<tblREFEthnic> tblREFEthnics { get; set; }
    }
}
