//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREFInstitution
    {
        public tblREFInstitution()
        {
            this.tblApplicantEdus = new HashSet<tblApplicantEdu>();
        }
    
        public string InstCd { get; set; }
        public string InstNm { get; set; }
        public bool MQAStatus { get; set; }
        public string InstCatCd { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDt { get; set; }
    
        public virtual ICollection<tblApplicantEdu> tblApplicantEdus { get; set; }
        public virtual tblREFInstitutionCat tblREFInstitutionCat { get; set; }
    }
}
