//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace SevenH.MMCSB.Atm.Persistance
{
    public partial class tblREFState
    {
        public tblREFState()
        {
            this.tblApplicants = new HashSet<tblApplicant>();
            this.tblREFCities = new HashSet<tblREFCity>();
        }
    
        public string StateCd { get; set; }
        public string State { get; set; }
        public string CountryCd { get; set; }
    
        public virtual ICollection<tblApplicant> tblApplicants { get; set; }
        public virtual ICollection<tblREFCity> tblREFCities { get; set; }
        public virtual tblREFCountry tblREFCountry { get; set; }
    }
}
