//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenH.MMCSB.Atm.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLog
    {
        public int UserLogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string LoginStatusCd { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tblREFLoginStatu tblREFLoginStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
